image: python:3.9

stages:
  - sync

sync_to_github:
  stage: sync
  before_script:
    - apt-get update && apt-get install -y git

    - export $(cat .env | xargs)

    - git config --global user.email "$GIT_USER_EMAIL"
    - git config --global user.name "$GIT_USER_NAME"

    - git clone https://$CI_SERVER_HOST/$CI_PROJECT_PATH.git repo
    - cd repo

    - git checkout master || echo "No master branch found" && exit 1

    - git remote | grep github || git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/F-A-C-C-T/pyfacct.git

  script:
    - git push github master
    - git push github --tags

  only:
    - master
